server:
  port: 8887

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://220.231.216.162:3306/ai_test?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: dooogo
    password: Dgkj*321
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      default-auto-commit: true
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter: stat,wall,log4j
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
